version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data/
      - ./bd:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./app
    command: python views.py
    volumes:
      - ./app:/usr/src/backend
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data_volume:

